
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-3
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-3
pull_requests: [{"author":{"id":"U_kgDOBtnu_g","is_bot":false,"login":"Kanagawa-okiNamiUra","name":""},"headRefName":"Albert-RiderApp_II","number":40,"title":"AW-Implemented RiderApplication Table&Form Component","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/40"},{"author":{"id":"U_kgDOBXuuuQ","is_bot":false,"login":"Danny-You","name":""},"headRefName":"Danny-Stryker-Improvement","number":39,"title":"Made Improvements for github to have faster Stryker runs","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/39"},{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-pages","number":31,"title":"Implemented Shift Pages (Create, Edit and Index)","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/31"},{"author":{"id":"MDQ6VXNlcjYyMzY5NTUy","is_bot":false,"login":"InariHimeko","name":""},"headRefName":"Wenxuan-Cell","number":30,"title":"Add User Cellphone","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/30"},{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-shiftForm","number":27,"title":"Lawrence shift form","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/27"},{"author":{"id":"MDQ6VXNlcjcyODI4OTQ1","is_bot":false,"login":"LolExile","name":"Johnny Wang "},"headRefName":"Johnny-DriverDash","number":26,"title":"First issue for Driver Dashboard","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/26"}]
