
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-3
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-3
pull_requests: [{"author":{"id":"U_kgDOBXznew","is_bot":false,"login":"lawrencewang30","name":""},"headRefName":"Lawrence-backend","number":20,"title":"ShiftController backend operations and tests","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/20"},{"author":{"id":"U_kgDOBXuuuQ","is_bot":false,"login":"Danny-You","name":""},"headRefName":"Danny-Swagger-Update","number":19,"title":"dy - update swagger csrf setting in application.properties","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/19"}]
