
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/proj-gauchoride-m23-9am-3
owner: ucsb-cs156-m23
repo_name: proj-gauchoride-m23-9am-3
pull_requests: [{"author":{"id":"U_kgDOBtnu_g","is_bot":false,"login":"Kanagawa-okiNamiUra","name":""},"headRefName":"Albert-RiderApp_III","number":44,"title":"AW--Implemented Index/Create/Edit Page for Rider Application from Member's View","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/44"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"Wenxuan-Cell-v2","number":43,"title":"Wenxuan cell v2","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/43"},{"author":{"id":"MDQ6VXNlcjYyMzY5NTUy","is_bot":false,"login":"InariHimeko","name":""},"headRefName":"Wenxuan-Cell","number":30,"title":"Add User Cellphone","url":"https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/pull/30"}]
